/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.diagnostico;

import dao.DiagnosticoDAO;
import dao.disciplina.DisciplinaProfessorDAO;
import dao.ProfessorDAO;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Diagnostico;
import model.disciplina.DisciplinaProfessor;
import model.Professor;

/**
 *
 * @author Aluno
 */
public class TelaDiagnostico extends javax.swing.JFrame {
    String dissigla;
    Professor professor = new Professor();
    ArrayList<DisciplinaProfessor> listaDeDisciplina;
    DisciplinaProfessor disciplinaSelecionada;
    Aluno aluno;
    /**
     * Creates new form TelaDiagnosticoAluno
     */
    public TelaDiagnostico() {
        initComponents();
        chamaProfessor();
        preencherCbxDisciplina();
        lblProfessor.setText("Professor: "+professor.getNome());
        Date data = new Date(System.currentTimeMillis());
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        jlTime.setText(formatador.format(data));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sldDesempenho = new javax.swing.JSlider();
        sldComportamento = new javax.swing.JSlider();
        sldFrequencia = new javax.swing.JSlider();
        sldPontualidade = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSuperacao = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProblema = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        lblDesempenho = new javax.swing.JLabel();
        lblComportamento = new javax.swing.JLabel();
        lblFrequencia = new javax.swing.JLabel();
        lblPontualidade = new javax.swing.JLabel();
        btnBuscarAluno = new javax.swing.JButton();
        lblAluno = new javax.swing.JLabel();
        cbxDisciplina = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jlTime = new javax.swing.JLabel();
        lblProfessor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Comportamento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Desempenho");

        sldDesempenho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDesempenhoStateChanged(evt);
            }
        });

        sldComportamento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldComportamentoStateChanged(evt);
            }
        });

        sldFrequencia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFrequenciaStateChanged(evt);
            }
        });
        sldFrequencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sldFrequenciaMouseClicked(evt);
            }
        });

        txtSuperacao.setColumns(20);
        txtSuperacao.setRows(5);
        jScrollPane1.setViewportView(txtSuperacao);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Problema");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Frequencia");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Pontualidade");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Superação");

        txtProblema.setColumns(20);
        txtProblema.setRows(5);
        jScrollPane2.setViewportView(txtProblema);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblDesempenho.setText("50");

        lblComportamento.setText("50");

        lblFrequencia.setText("50");

        lblPontualidade.setText("50");

        btnBuscarAluno.setText("Buscar por alunos");
        btnBuscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlunoActionPerformed(evt);
            }
        });

        lblAluno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAluno.setText("Aluno: Sem nome");

        cbxDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxDisciplinaMouseClicked(evt);
            }
        });
        cbxDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDisciplinaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Disciplina");

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Diagnóstico do Aluno");

        jlTime.setForeground(new java.awt.Color(255, 255, 255));
        jlTime.setText("DATA ATUAL : ");

        lblProfessor.setText("Professor: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlTime, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProfessor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTime)
                    .addComponent(lblProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sldFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFrequencia))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sldComportamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblComportamento))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sldDesempenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBuscarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxDisciplina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDesempenho))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sldPontualidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSalvar)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPontualidade)))))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(cbxDisciplina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAluno)
                    .addComponent(btnBuscarAluno))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(sldDesempenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(lblDesempenho))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(sldComportamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblComportamento))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(sldFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPontualidade)
                            .addComponent(sldPontualidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(92, 92, 92)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFrequencia)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlunoActionPerformed
        // TODO add your handling code here:
        TelaListaAluno view1 = new TelaListaAluno();
        view1.setTelaDiagnostico(this);
        view1.setVisible(true);
    }//GEN-LAST:event_btnBuscarAlunoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        
       if(!txtProblema.getText().trim().isEmpty() &&! txtSuperacao.getText().trim().isEmpty()){
            
        try {
            DiagnosticoDAO dao = new DiagnosticoDAO();     
            int sld1 = sldDesempenho.getValue();
            int sld2 = sldComportamento.getValue();
            int sld3 = sldFrequencia.getValue();
            int sld4 = sldPontualidade.getValue();
            String txt1 = txtProblema.getText();
            String txt2 = txtSuperacao.getText();
            String sigla = disciplinaSelecionada.getDissigla();
            int numero = disciplinaSelecionada.getNumero();
            String dtinicio = disciplinaSelecionada.getDtInicio();
            Diagnostico bean = new Diagnostico(sld1,sld2,sld3,sld4,txt1,txt2,sigla,numero,dtinicio,aluno.getMatricula());
            
            if(dao.cadastrar(bean)){
                showMsg("Cadastrado com sucesso");
                limparCampos();
            }else{
                limparCampos();
                showMsg("Erro ao cadastrar");
            }
            
        } catch (Exception e) {
        }
           
       }else{
            showMsg("Preencha todos os campos!");
       }   
       
    }//GEN-LAST:event_btnSalvarActionPerformed

    
    private void cbxDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxDisciplinaMouseClicked
        // TODO add your handling code here:
        int index = cbxDisciplina.getSelectedIndex();
        disciplinaSelecionada = listaDeDisciplina.get(index);
        disciplinaSelecionada.setPromatricula(professor.getMatricula());
    }//GEN-LAST:event_cbxDisciplinaMouseClicked

    private void cbxDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDisciplinaActionPerformed
        // TODO add your handling code here:
        int index = cbxDisciplina.getSelectedIndex();
        disciplinaSelecionada = listaDeDisciplina.get(index);
        disciplinaSelecionada.setPromatricula(professor.getMatricula());
         
    }//GEN-LAST:event_cbxDisciplinaActionPerformed

    private void sldFrequenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sldFrequenciaMouseClicked
        // TODO add your handling code here:
        lblFrequencia.setText(Integer.toString(sldFrequencia.getValue()));
    }//GEN-LAST:event_sldFrequenciaMouseClicked

    private void sldDesempenhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDesempenhoStateChanged
        // TODO add your handling code here:
        lblDesempenho.setText(Integer.toString(sldDesempenho.getValue()));
    }//GEN-LAST:event_sldDesempenhoStateChanged

    private void sldComportamentoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldComportamentoStateChanged
        // TODO add your handling code here:
        lblComportamento.setText(Integer.toString(sldComportamento.getValue()));
    }//GEN-LAST:event_sldComportamentoStateChanged

    private void sldFrequenciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFrequenciaStateChanged
        // TODO add your handling code here:
         lblFrequencia.setText(Integer.toString(sldFrequencia.getValue()));
    }//GEN-LAST:event_sldFrequenciaStateChanged

    private void preencherCbxDisciplina(){
        try {
            DisciplinaProfessorDAO dao = new DisciplinaProfessorDAO();
            listaDeDisciplina = dao.consultarDisciplinaProfessor(professor.mat);
            Vector linhas = new Vector();
            for (DisciplinaProfessor lista : listaDeDisciplina) {
                Vector linha = new Vector();
                linha.add(lista.getDissigla());
                linhas.add(linha);
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel(linhas);
            cbxDisciplina.setModel(model); 
        } catch (Exception e) {
         
        }
    }
    
    private void limparCampos(){
        sldDesempenho.setValue(50);
        sldComportamento.setValue(50);
        sldFrequencia.setValue(50);
        sldPontualidade.setValue(50);
        txtProblema.setText("");
        txtSuperacao.setText("");
    }
    
    
    
    private void chamaProfessor(){
        try {
            ProfessorDAO dao = new ProfessorDAO(); 
            professor = dao.consultarSigla(Professor.mat);
        } catch (Exception ex) {
            Logger.getLogger(TelaDiagnostico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public DisciplinaProfessor getDisciplinaProfessor(){
        return disciplinaSelecionada;
    }
    
    public void setAluno(Aluno aluno){
        this.aluno = aluno;
        lblAluno.setText(aluno.getNome());
    }
    
    private void showMsg(String msg){
       JOptionPane.showMessageDialog(null, msg);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDiagnostico().setVisible(true);
            }
        });
    }
    
    
//    public void addBtnBuscarAlunoListener(ActionListener listener){
//        this.btnBuscarAluno.addActionListener(listener);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAluno;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxDisciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlTime;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JLabel lblComportamento;
    private javax.swing.JLabel lblDesempenho;
    private javax.swing.JLabel lblFrequencia;
    private javax.swing.JLabel lblPontualidade;
    private javax.swing.JLabel lblProfessor;
    private javax.swing.JSlider sldComportamento;
    private javax.swing.JSlider sldDesempenho;
    private javax.swing.JSlider sldFrequencia;
    private javax.swing.JSlider sldPontualidade;
    private javax.swing.JTextArea txtProblema;
    private javax.swing.JTextArea txtSuperacao;
    // End of variables declaration//GEN-END:variables
}
